suites:
    pipeline_suite:
        namespace: Kiboko\Component\Pipeline
        psr4_prefix: Kiboko\Component
        spec_path: tests/%paths.config%
        src_path: tests/%paths.config%
    jenkinsfile_suite:
        namespace: Kiboko\Component\Jenkinsfile
        psr4_prefix: Kiboko\Component
        spec_path: tests/%paths.config%
        src_path: tests/%paths.config%
